displayName=Clicker Training
author=ju.niper
support=https://github.com/pyonium/clicker-training-osrs
description=Leveled up! Good doggy!
tags=levelup, level, dog
plugins=com.pyonium.clicker.ClickerPlugin